# Generated by Django 4.1 on 2022-09-09 01:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='국가명')),
                ('code', models.CharField(max_length=2, verbose_name='국가코드')),
                ('dcode', models.CharField(max_length=4, verbose_name='국가번호')),
            ],
            options={
                'verbose_name': '국가',
                'verbose_name_plural': '국가',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)], verbose_name='수량')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='비용')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country', verbose_name='국가')),
            ],
            options={
                'verbose_name': '배송비',
                'verbose_name_plural': '배송비',
            },
        ),
    ]
