# Generated by Django 4.1 on 2022-09-10 01:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 9, 10), verbose_name='주문일자')),
                ('pay_state', models.CharField(choices=[('결제완료', '결제완료'), ('상품준비중', '상품준비중'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('주문취소', '주문취소')], default='결제완료', max_length=10, verbose_name='주문상태')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)], verbose_name='수량')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격')),
                ('delivery_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='배송비')),
                ('buyr_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='배송도시')),
                ('buyr_zipcode', models.CharField(max_length=10, verbose_name='우편번호')),
                ('buyr_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='주문자명')),
                ('delivery_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='송장번호')),
                ('buyr_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country', verbose_name='배송국가')),
            ],
            options={
                'verbose_name': '주문내역',
                'verbose_name_plural': '주문내역',
            },
        ),
    ]
