# Generated by Django 4.1 on 2022-09-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('order', '0002_alter_order_date_alter_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupon.coupon', verbose_name='쿠폰'),
        ),
    ]
