# Generated by Django 4.1 on 2022-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyr_name',
            field=models.CharField(default='최보미', max_length=30, verbose_name='주문자명'),
            preserve_default=False,
        ),
    ]
