# Generated by Django 4.1 on 2022-09-14 00:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('배송비 할인', '배송비 할인'), ('% 할인', '% 할인'), ('정액 할인', '정액 할인')], max_length=16, verbose_name='유형')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='할인값')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='발급일')),
                ('expr_date', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('used_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='사용횟수')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 할인액')),
            ],
            options={
                'verbose_name': '쿠폰종류',
                'verbose_name_plural': '쿠폰종류',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='코드')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용여부')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupontype', verbose_name='종류')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
            },
        ),
    ]
