# Generated by Django 4.1 on 2022-09-15 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupontype_min_price_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontype',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='최소금액조건'),
        ),
        migrations.AlterField(
            model_name='coupontype',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인값'),
        ),
    ]
